export default [
    {
        id: 1,
        title: 'Spellbook Magic with Katie',
        description: 'Learn how to make your own grimmoire',
        price: 30,
        coverImg: 'book--magic.jpg',
        stats: {
            rating: 4.8,
            reviewCount: 22,
        },
        location: 'USA',
        openSpots: 0,
    },
    {
        id: 2,
        title: 'Candle Magic 101',
        description: 'Learn the meaning of different candles and the usage of them. Practise candle magic with your exeprienced host Matilda',
        price: 45,
        coverImg: 'candle--magic.jpg',
        stats: {
            rating: 5.0,
            reviewCount: 12,
        },
        location: 'Online',
        openSpots: 2,
    },
    {
        id: 3,
        title: 'Green Witch arsenal',
        description: 'Take a peak into Green Witches Herban cabinets with a guidence on how to start your own Green practice',
        price: 60,
        coverImg: 'herbal--magic.jpg',
        stats: {
            rating: 4.6,
            reviewCount: 34,
        },
        location: 'Canada',
        openSpots: 4,
    },
    {
        id: 4,
        title: 'Join biggest online Coven',
        description: 'Introduction to the always growing online Coven, find your new Witchy home',
        price: 15,
        coverImg: 'coven--magic.jpg',
        stats: {
            rating: 5.0,
            reviewCount: 56,
        },
        location: 'Online',
        openSpots: 10,
    },
    {
        id: 5,
        title: 'Brew your prefect morning',
        description: 'Learn how to enchance and enchant your coffee or tea.',
        price: 55,
        coverImg: 'tea--magic.jpg',
        stats: {
            rating: 4.7,
            reviewCount: 30,
        },
        location: 'USA',
        openSpots: 0,
    },
    {
        id: 6,
        title: 'Witch in the woods dance practice',
        description: 'The hostess - Witch in the woods - will teach you how to be a fire witch dancing around the bonfires in the midnight',
        price: 125,
        coverImg: 'Fire--dance.jpg',
        stats: {
            rating: 4.9,
            reviewCount: 7,
        },
        location: 'Portugal',
        openSpots: 2,
    },
]