export default [
    {
        id: 1,
        title: 'Intense colors',
        location: 'Bali',
        description: 'Beautiful island full of intense colors, smells and taste. So many colorful flowers everywhere, colors like you only see in pictures. Black beaches and never ending festivals with roosters in baskets on every corner.',
        imageUrl: 'bali.jpg',
        plus: 'Fruits so sweet you can eat lemons like apples',
    },
    {
        id: 2,
        title: 'Only blue water',
        location: 'Maledivien',
        description: 'Blue ocean no matter where you look. Enjoy the sun on the pure white cheaches. The waters are so clear you can see the ocean reef and colorful fishes. Float in the ocean and enjoy pure bliss. ',
        imageUrl: 'maledivien.jpg',
        plus: 'You have never seen sand so white',
    },
    {
        id: 3,
        title: 'Raw beauty',
        location: 'Tatry - Poland',
        description: 'Raw mountain range , beautiful no matter the season.  Untouched by human hands with nature surrounding you at all times. Beautiful climbs and fresh crisp air',
        imageUrl: 'tatry.jpg',
        plus: 'Drink water straight out of the source on your hike',
    },
    {
        id: 4,
        title: 'My greek holiday',
        location: 'Greece',
        description: 'Beautiful islands with rich history. Walking the streets that stood there for millennials, going back to the times when olympian gods were still around. Enjoy out of this world food! ',
        imageUrl: 'greece.jpg',
        plus: 'Great atmosphere',
    },
    {
        id: 5,
        title: 'Clifs and waterfalls',
        location: 'Madeira',
        description: 'Raw and beautiful island full of cliffs and the never ending smell of eucalyptus. This unique mountain island will never disappoint. Every part is like its own little ecosystem with new things to discover and experience. You must try the flat chicken and chestnut bread.',
        imageUrl: 'madeira.jpg',
        plus: 'Take a ride on the cliffs edge',
    },
    {
        id: 6,
        title: 'Hot and beautiful',
        location: 'Sayshelle',
        description: 'Explore beautiful tropical islands and drink coconuts fresh out of the palms. True paradise. Hot sun, white sandy beaches and beautiful blue ocean. ',
        imageUrl: 'seyshelle.jpg',
        plus: 'True tropical paradise ',
    },

]